#!/bin/bash
# WF 2020-03-25
os=$(uname -a)
case $os in
  Darwin*)
   pip="sudo -H pip"
   install="sudo port install"
   ;;
  *)
   pip="pip3"
   if [ "$USER" = "travis" ]
   then
     pip="pip"
   fi
   install="sudo apt-get install"
   ;;
esac
#$install python3-pip
sudo -H $pip install -r requirements.txt
