#!/bin/bash
# WF 2020-03-26
# create a release see https://packaging.python.org/tutorials/packaging-projects/
scripts/doc -d

# Commit with a message that includes the current ISO timestamp
git commit -a -m "release commit"
git push
