#!/bin/bash
# WF 2020-10-31
# wrapper for wikipush python
script=$(python -c "import os;import sys;print (os.path.realpath(sys.argv[1]))" $BASH_SOURCE)
scriptname=$(basename $script)
scriptdir=$(dirname $script)
base=$scriptdir/..
export PYTHONPATH="${PYTHONPATH}:$base"
case $scriptname in
   "wikipush")
	python -m wikibot.wikipush "$@"
	;;
   "wikiedit")
   	python -m wikibot.wikiedit "$@"
   	;;
   "wikiuser")
	python -m wikibot.wikiuser "$@"
	;;
   "wikinuke")
   	python -m wikibot.wikinuke "$@"
   	;;
   *)
	echo "undefined wikipush script behavior:  $scriptname"
	;;
esac
